#!/bin/bash

set -e
set -o pipefail

read folder
folder=$(echo "$folder" | base64 -d) || {
   echo 'error: the folder passed as argument could not be decoded'
}

if [ "$folder" == "" ] ; then
    echo 'error: an argument specifying the folder to be shared is required' >&2
    exit 4
fi

if [ ! -d "$folder" ] ; then
    echo "error: the folder to be shared $folder does not exist or is not a directory" >&2
    exit 2
fi

echo ok

exec /usr/sbin/diod -f -r 0 -w 1 -n -H -e "$folder" -S || {
    ret=$?
    echo "error: diod is not installed" >&2
    exit $ret
}
